In [10]:
import pandas as pd
from utils import generate_half_year_dates

In [13]:
data_moex = pd.read_csv("data/returns_of_stok.csv", index_col="TRADEDATE", parse_dates=["TRADEDATE"])
data_moex = data_moex['MOEX'][data_moex.index  >= "2014-01-01 00:00:00"]

In [5]:
data_por = pd.read_csv('data/portfels.csv')

In [6]:
data_por

        period      beta  future_income  fact_income  moex_income
0   2014-07-31  0.378964      10.948230    10.777115     0.325153
1   2015-01-31  0.355511      11.717315    11.714037     0.016144
2   2015-07-31  0.340463      11.877156    12.638546     0.454591
3   2016-01-31  0.356084      11.752364    12.141230     0.335692
4   2016-07-31  0.346183      11.884464    12.509048     0.294316
5   2017-01-31  0.317548      12.377596    12.627257    -0.377143
6   2017-07-31  0.307568      12.347899    12.625596     0.106664
7   2018-01-31  0.317583      12.327464    10.620169    -0.230882
8   2018-07-31  0.399770      10.711850    12.093076    -0.164779
9   2019-01-31  0.320468      12.178777    12.454895     0.006622
10  2019-07-31  0.336538      11.944543    11.720405     0.302734
11  2020-01-31  0.356501      11.690899     9.235309     0.298765
12  2020-07-31  0.440231      10.208476    12.805448     0.283316
13  2021-01-31  0.291001      12.844435    12.969958     0.126265
14  2021-07-31  0.286215      12.882860     9.838497    -0.281288
15  2022-01-31  0.395069      10.779574     8.881595    -0.854480
16  2022-07-31  0.460686       9.314001     9.250549     0.293224
17  2023-01-31  0.486219       9.393512    10.824794     0.378455
18  2023-07-31  0.406947      10.829801    10.669330     0.683215
19  2024-01-31  0.416786      10.781593     8.975648     0.220275
20  2024-07-31  0.501746       9.076043     7.941268    -0.354791

In [14]:
periods = generate_half_year_dates(data_moex)
periods

c:\Users\EGaydi01\Desktop\diploma-1\utils.py:60: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  return pd.date_range(start=min_date, end=max_date, freq="6M").tolist()

[Timestamp('2014-01-31 00:00:00'),
 Timestamp('2014-07-31 00:00:00'),
 Timestamp('2015-01-31 00:00:00'),
 Timestamp('2015-07-31 00:00:00'),
 Timestamp('2016-01-31 00:00:00'),
 Timestamp('2016-07-31 00:00:00'),
 Timestamp('2017-01-31 00:00:00'),
 Timestamp('2017-07-31 00:00:00'),
 Timestamp('2018-01-31 00:00:00'),
 Timestamp('2018-07-31 00:00:00'),
 Timestamp('2019-01-31 00:00:00'),
 Timestamp('2019-07-31 00:00:00'),
 Timestamp('2020-01-31 00:00:00'),
 Timestamp('2020-07-31 00:00:00'),
 Timestamp('2021-01-31 00:00:00'),
 Timestamp('2021-07-31 00:00:00'),
 Timestamp('2022-01-31 00:00:00'),
 Timestamp('2022-07-31 00:00:00'),
 Timestamp('2023-01-31 00:00:00'),
 Timestamp('2023-07-31 00:00:00'),
 Timestamp('2024-01-31 00:00:00'),
 Timestamp('2024-07-31 00:00:00')]

In [25]:
res = []
for per in periods:
    stop = per + pd.DateOffset(months=6)
    period_data = data_moex[(data_moex.index >= per) & (data_moex.index < stop)].copy()
    print(f"{per}-{stop}:  {period_data.mean()*100*2:.2f}  ")
    res.append(period_data.mean()*100*2)

2014-01-31 00:00:00-2014-07-31 00:00:00:  -0.19
2014-07-31 00:00:00-2015-01-31 00:00:00:  0.33
2015-01-31 00:00:00-2015-07-31 00:00:00:  0.02
2015-07-31 00:00:00-2016-01-31 00:00:00:  0.45
2016-01-31 00:00:00-2016-07-31 00:00:00:  0.34
2016-07-31 00:00:00-2017-01-31 00:00:00:  0.29
2017-01-31 00:00:00-2017-07-31 00:00:00:  -0.38
2017-07-31 00:00:00-2018-01-31 00:00:00:  0.11
2018-01-31 00:00:00-2018-07-31 00:00:00:  -0.23
2018-07-31 00:00:00-2019-01-31 00:00:00:  -0.16
2019-01-31 00:00:00-2019-07-31 00:00:00:  0.01
2019-07-31 00:00:00-2020-01-31 00:00:00:  0.30
2020-01-31 00:00:00-2020-07-31 00:00:00:  0.30
2020-07-31 00:00:00-2021-01-31 00:00:00:  0.28
2021-01-31 00:00:00-2021-07-31 00:00:00:  0.13
2021-07-31 00:00:00-2022-01-31 00:00:00:  -0.28
2022-01-31 00:00:00-2022-07-31 00:00:00:  -0.85
2022-07-31 00:00:00-2023-01-31 00:00:00:  0.29
2023-01-31 00:00:00-2023-07-31 00:00:00:  0.38
2023-07-31 00:00:00-2024-01-31 00:00:00:  0.68
2024-01-31 00:00:00-2024-07-31 00:00:00:  0.22
2024-07-31 00:00:00-2025-01-31 00:00:00:  -0.35

In [26]:
len(res), len(data_por)

(22, 21)

In [24]:
res

[-0.1942679888320459,
 0.32515278271848497,
 0.016144477106634716,
 0.45459139939985505,
 0.3356923378238703,
 0.29431631375979334,
 -0.37714259445296744,
 0.10666437783883806,
 -0.23088159012289158,
 -0.16477928540704292,
 0.00662238174471041,
 0.30273388008052493,
 0.29876516975665374,
 0.2833157876092864,
 0.12626519676222317,
 -0.28128754004408846,
 -0.8544803621486831,
 0.29322413488001203,
 0.3784553814545155,
 0.6832147197929535,
 0.22027471391865516,
 -0.35479130383217966]

In [27]:
data_por['MOEX'] = res[:-1]
data_por

,period,beta,future_income,fact_income,moex_income,MOEX
0,2014-07-31,0.378964,10.948230,10.777115,0.325153,-0.194268
1,2015-01-31,0.355511,11.717315,11.714037,0.016144,0.325153
2,2015-07-31,0.340463,11.877156,12.638546,0.454591,0.016144
3,2016-01-31,0.356084,11.752364,12.141230,0.335692,0.454591
4,2016-07-31,0.346183,11.884464,12.509048,0.294316,0.335692
5,2017-01-31,0.317548,12.377596,12.627257,-0.377143,0.294316
6,2017-07-31,0.307568,12.347899,12.625596,0.106664,-0.377143
7,2018-01-31,0.317583,12.327464,10.620169,-0.230882,0.106664
8,2018-07-31,0.399770,10.711850,12.093076,-0.164779,-0.230882
9,2019-01-31,0.320468,12.178777,12.454895,0.006622,-0.164779
10,2019-07-31,0.336538,11.944543,11.720405,0.302734,0.006622
11,2020-01-31,0.356501,11.690899,9.235309,0.298765,0.302734
12,2020-07-31,0.440231,10.208476,12.805448,0.283316,0.298765
13,2021-01-31,0.291001,12.844435,12.969958,0.126265,0.283316
14,2021-07-31,0.286215,12.882860,9.838497,-0.281288,0.126265
15,2022-01-31,0.395069,10.779574,8.881595,-0.854480,-0.281288
16,2022-07-31,0.460686,9.314001,9.250549,0.293224,-0.854480
17,2023-01-31,0.486219,9.393512,10.824794,0.378455,0.293224
18,2023-07-31,0.406947,10.829801,10.669330,0.683215,0.378455
19,2024-01-31,0.416786,10.781593,8.975648,0.220275,0.683215
20,2024-07-31,0.501746,9.076043,7.941268,-0.354791,0.220275